### ISSUE TITLE
Get logged in user from the client side?

### ISSUE THREAD

**Issue by Marcoevich** [hapijs/hapi-auth-cookie#105]
I use hapi-auth-cookie with success to authenticate the users in our app. One problem I am currently facing is how to get the logged in userId from the clientside, when request object is not available? This happens in a clientside controller for example. 

I can do this with a route back to the server, then return the userId from the request in the route handler. However I feel this should be simpler. Is it possible to extract this information from the stored cookie in the client? Or are there any other options I can try?

Thx a lot for your plugin!

**Comment by peturh** [comment]
I also ran into this problem. I did what you didn't want to do. I guess it could be more simple.

     plugin.route({
            method: 'GET',
            path: '/getCredentials',
            config: {
                auth: 'session',
                handler: function (request, reply) {
                    reply(request.auth.credentials);
                }
            }
        });

**Comment by Marcoevich** [comment]
Hi Peturh, I have also done it via a route now :) If anyone knows a way to extract this information directly from the cookie, feel free to let us know!

**Comment by jaw187** [comment]
By design, the client can't decrypt the cookie.

**Comment by bartonhammond** [comment]
I'm very confused w/ all this, so excuse my ignorance.

I am using ReactNative, a mobile framework. I am testing using GenyMotion for Android emulation.

For the life of me, I can't figure out when the authentication is successful from my client

I am using Hapi Bell oAuth for GitHub, my server implementation is:

```
  var authCookieOptions = {
    password: 'cookie-encryption-password', //Password used for encryption
    cookie: 'sitepoint-auth', // Name of cookie to set
    isSecure: false
  };
  server.auth.strategy('site-point-cookie', 'cookie', authCookieOptions);
  var bellAuthOptions = {
    provider: 'github',
    password: 'github-encryption-password', //Password used for encryption
    clientId: 'd2c19dc0',//'YourAppId',
    clientSecret: '13319cdc2d81cfd5',//'YourAppSecret',
    isSecure: false //true for https
  };
  server.auth.strategy('github-oauth', 'bell', bellAuthOptions);
  server.auth.default('site-point-cookie');

then
    method: ['GET','POST'],
      path: '/login',
      config: {
        auth: 'github-oauth',
       handler: function (request, reply) {
          if (request.auth.isAuthenticated) {
            request.cookieAuth.set(request.auth.credentials);
            return reply('Hello ' + request.auth.credentials.profile.displayName);
          }
            return reply('Not logged in...').code(401);
        }
```
I can put a breakpoint right after the 'isAuthenticated' and see it sets the 'cookieAuth'.

How do I determine, in the client, that the '/login' is authenticated?  

Sorry for my ignorance, i am very confused w/ all this
