### ISSUE TITLE
Validate function in readme not working

### ISSUE THREAD

**Issue by Marcoevich** [hapijs/hapi-auth-cookie#106]
I tried to use the validate function in your readme like this:

        validateFunc: function (request, session, callback) {

            cache.get(session.sid, (err, cached) => {

                if (err) {
                    return callback(err, false);
                }

                if (!cached) {
                return callback(null, false);
            }

            return callback(null, true, cached.account);
        });
        }

I get various syntax errors, like "expression statement is not assignment or call" on `app.get()` 

Could you test this function and let me know if it still works for you?

**Comment by jaw187** [comment]
Works fine for me.  Feel free to share your full code if you need additional review.

**Comment by Marcoevich** [comment]
I fixed this, Needed to set javascript language versions to 'ECMAScript 6' in Jetbrains Webstorm settings :)

Thx, i'll close this for you.
