### ISSUE TITLE
request.cookieAuth.clear() vs request.auth.session.clear()

### ISSUE THREAD

**Issue by bf** [hapijs/hapi-auth-cookie#108]
I've been using `request.auth.session.clear()` in my project for a long time, and now noticed that it doesn't really work any more. The next request after the function call is still authenticated, and only if you refresh again the unauthorized page is shown.

I have revisited the example section and now it seems to be `request.cookieAuth.clear()`, which indeed works correctly and solves the issue I encoutered while using `request.auth.session.clear()`. 

Unfortunately I was unable to find any specifics about `request.cookieAuth` in the documentation.

I am running `v3.1.0`, where `request.auth.session.clear()` is used in the examples. I wonder why the `request.cookieAuth` object is already there and works in my case? I am using hapi `8.8.1`.

**Comment by bf** [comment]
Okay, it seems I misinterpreted the errors I was given and the issue is not being solved by using the  `request.cookieAuth`.

Given that I am running hapi `8.8.1` does it make sense to upgrade hapi-auth-cookie to current `6.x.x` @hueniverse ?

**Comment by hueniverse** [comment]
I am not the right person to ask. I don't use this module.

**Comment by bf** [comment]
Ok thanks for your reply. Are you using an alternative module for cookie-based sessions or no such sessions at all?

I'll reopen this issue when I have upgraded to both latest versions of hapi and this plugin. Keep up the good work!

**Comment by jaw187** [comment]
@bf The functionality of `request.auth.session.clear` and `request.cookieAuth.clear` are one and the same.  Changes to Hapi core required moving away from `request.auth.session`.  Let me know if you need more assistance reviewing your issues.
