### ISSUE TITLE
Registering two strategies

### ISSUE THREAD

**Issue by antony** [hapijs/hapi-auth-cookie#111]
Hi,

I have a scenario whereby I have a consumer api and a merchant api. These APIs use different cookies -  one called 'merchant' and one called 'consumer'.

I notice from the documentation that the cookie-auth 'scheme' cannot be registered more than once (due to request decoration). Does this therefore imply that I can't set up two strategies (using ```server.auth.strategy(...)```), one for consumer and one for merchant, and use:

```
auth: {
  strategy: 'merchant' // or consumer
}
```

to validate authentication on different routes?

The reason I ask is that since registering the consumer strategy, it seems that my merchant login endpoint is returning a cookie named after the consumer strategy, even though the route auth configuration is correct.

If so - is there a way around this with some code changes to the module? Or would it require a significant rework?

Thanks in advance,
Antony

**Comment by jaybrueder** [comment]
Also a problem I am facing right now!

**Comment by mtharrison** [comment]
Can you show a small example of code to illustrate the issue? You should be able to register as many strategies as you like, provided you only want to authenticate with one of them per route.

**Comment by jaybrueder** [comment]
Here is an example form my project.

I want to define two auth strategies. One for the User model and one for the Admin model.

```
server.register(require('hapi-auth-cookie'), function (err) {
    if (err) console.log(err);

    server.auth.strategy('user', 'cookie', {
      password: 'abcdefghijklmnopqrstuvwxyz123456',
      redirectTo: '/login',
      isSecure: false
    });

    server.auth.strategy('admin', 'cookie', {
      password: 'abcdefghijklmnopqrstuvwxyz654321',
      redirectTo: '/admin/login',
      isSecure: false
    });

  });
```

If I try to start the server with this code, I get the following error message:

```
/Users/jaybrueder/repositories/hapi_project/node_modules/hapi/node_modules/hoek/lib/index.js:732
    throw new Error(msgs.join(' ') || 'Unknown error');
    ^

Error: State already defined: sid
    at Object.exports.contain.exports.reachTemplate.exports.assert.condition [as assert] (/Users/jaybrueder/repositories/hapi_project/node_modules/hapi/node_modules/hoek/lib/index.js:732:11)
```

The authentication works perfectly with only one authentication strategy in place.

I fairly new to the Hapi framework and NodeJS in general. So this could very well be just a simple beginners mistake. However, I would be happy for any help.

**Comment by jaybrueder** [comment]
I am using:

```
"hapi": "^13.0.0",
"hapi-auth-cookie": "^6.0.0"
```

**Comment by antony** [comment]
I am using the same versions, and my code is almost identical.

I am currently working around the problem by using two different connections, which seems to isolate the plugin's strategies, and resolve the issue nicely, but I really need to use both cookies on one connection (albeit different routes).

My code doesn't fail at the same point though. I have a **lot** of tests around it and the exact issue is that my assertions state that upon login using 'try' auth, I get back the last-created cookieName

I.e. if I log in as a merchant (merchantCookie: 'Fe26**...', I get back consumerCookie: 'Fe26**...

the last initiated configuration overwrites the first.

I'll post code tomorrow if this isn't clear.

**Comment by mtharrison** [comment]
My mistake, it looks like the decoration is added to the `request` object globally for the first registered strategy. Any future use of `request.cookieAuth` will refer back to that strategy. Some changes would have to be made, but this scheme should be able to support multiple strategies IMO.

One of the things that the API would need to support is specifying which strategy you're setting a cookie for in a handler. Any thoughts @jaw187?

**Comment by antony** [comment]
@mtharrison Nope, they can either be a merchant or consumer, not both.

**Comment by jaw187** [comment]
Just so we're all on the same page.  The original error is due to the strategies not setting the `cookie` options, which will default to `'sid'`.  However the issue as reported is real since the implementation decorates request with the same name each time the strategy is registered.  It was a pretty easy change which I've thrown together and will submit a PR for right now.
