### ISSUE TITLE
Upgrade from 3.0.1 to 6.0.0

### ISSUE THREAD

**Issue by StarpTech** [hapijs/hapi-auth-cookie#113]
I just want to upgrade hapi-auth-cookie 3.0.1 to 6.0.0

Hapi: From 8.8.x to 12.1.0

```
server.auth.strategy('session', 'cookie', 'try', {
        password: config.sessionPassword,
        validateFunc: Session.getValidateFunc(),
        isSecure: !!config.server.web.tls,
        clearInvalid: true,
        redirectOnTry: false,
        keepAlive: true,
        redirectTo: config.server.web.uri + '/auth/signin',
        appendNext: true,
        cookie: 'sid',
        ttl: 365 * 24 * 60 * 60 * 1000 // 1 Year
    });
```

I'm facing to following problems:

`request.cookieAuth.clear()`
message: Uncaught error: request.cookieAuth.clear is not a function stack: TypeError: Uncaught error: request.cookieAuth.clear is not a function

`request.cookieAuth().clear()`
message: Uncaught error: Cannot read property 'auth' of undefined stack: TypeError: Uncaught error: Cannot read property 'auth' of undefined

**Comment by jaw187** [comment]
@StarpTech Can you send me a gist which duplicates this?

**Comment by StarpTech** [comment]
Hi @jaw187 I will try to provide it ASAP.

**Comment by jaw187** [comment]
@StarpTech Is this still a problem?

**Comment by StarpTech** [comment]
@jaw187 yes, but I have no time to reproduce this error. I will try it in the next days.

**Comment by jaw187** [comment]
@StarpTech ping

**Comment by StarpTech** [comment]
Hi @jaw187 problem solved. I had to upgrade Glue to the lastest version and respect multiple connections like in https://github.com/hapijs/university/issues/187
Thank you.
