### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by spiffytech** [hapijs/hapi-auth-cookie#116]
Please include a changelog, to help with upgrades. E.g., it's hard for me to tell the impact of upgrading from v5.0.0 to v6.1.0, even looking at the commit history. The major version bump suggests breaking changes, but there's no documentation on what those are.

**Comment by Marsup** [comment]
See https://github.com/hapijs/good/issues/434 for the answer you will probably have.

**Comment by jaw187** [comment]
All of the commits are effectively a change log.  Reviewing the changes to the examples and tests will provide the best view on what it takes to upgrade.  If you have any specific questions, please let me know.
