### ISSUE TITLE
`cookieAuth` or settings.requestDecoratorName

### ISSUE THREAD

**Issue by jney** [hapijs/hapi-auth-cookie#117]
just a quick question, i was reading the code an was wondering where `cookieAuth` https://github.com/hapijs/hapi-auth-cookie/blob/master/lib/index.js#L131 property came from ?

isn't it suppose to be:

```js
request[settings.requestDecoratorName].reply = reply
```

fyi i didn't make a pull request because i haven't test the code, i was just try to understand how you got access to `reply` in `decorate` context. better useless question than a mistake.

**Comment by jaw187** [comment]
`'cookieAuth'` is the default value for `requestDecoratorName`

```
    requestDecoratorName: Joi.string().default('cookieAuth')
```

**Comment by jaw187** [comment]
Thanks!  Great catch, I misunderstood what you were reporting at first.  Fix is in and broken version has been unpublished
