### ISSUE TITLE
upgrading from 5.0.0 to ^6.0.0

### ISSUE THREAD

**Issue by seekasra** [hapijs/hapi-auth-cookie#119]
We get the error of : 

> Error: Request interface decoration already defined: cookieAuth

.

**Comment by jaw187** [comment]
Are you defining more than one strategy?

**Comment by seekasra** [comment]
no.

**Comment by jaw187** [comment]
The only way that error is going to be thrown is if `server.decorate` is called twice.  Would you be able to post a gist of what you're working with?

**Comment by seekasra** [comment]
Yes, we are using it many times, since we just need it.

**Comment by jaw187** [comment]
?

**Comment by stephenmuss** [comment]
@jaw187 I have had the same problem too.

In my case I am using Glue and have multiple connections/plugins which use hapi-auth-cookie.

I have set up a demo with a similar config (note there are no routes defined) which replicates the issue.

See https://github.com/stephenmuss/hapi-auth-cookie-error-demo.

**Comment by jaw187** [comment]
@stephenmuss I just submitted https://github.com/stephenmuss/hapi-auth-cookie-error-demo/pull/1 to show how to avoid the error when using cookie auth more than once

@seekasra This may apply to you.

**Comment by antony** [comment]
Hm - I have this exact same problem too, yet I am only using the plugin once. I have five connections, but define the auth on the main 'server' connection:

```
server.auth.strategy('cookie-auth', 'cookie', {
          password: config.security.all.encryptionKey,
          cookie: config.security.all.cookieName,
          isSecure: false,
          validateFunc: cookieCutter.validateCookie
      });
```

Is it possible that the other connectors cause decorate to be called multiple times?

**Comment by jaw187** [comment]
@antony You just need to add a unique `requestDecoratorName` property to each strategy.

**Comment by antony** [comment]
But I don't have multiple strategies :) one strategy, multiple connections.

**Comment by jaw187** [comment]
Ah, you're right.  I didn't look at the bar plugin :/.  So this might be a Hapi core issue.  It's gonna require a fair amount of digging, stand by.

**Comment by antony** [comment]
No problem! Standing by!

**Comment by jaw187** [comment]
@antony Is your goal to apply the strategy to both connections?  If not, then the quickest fix is to do something like this
```javascript
    const foo = server.select('foo');
    foo.auth.strategy('session', 'cookie', true, {
```

**Comment by antony** [comment]
Yeah I really need it over three distinct connections. I have basic auth on
another and bearer auth on another. So five in total.

**Comment by gordysc** [comment]
I hit the same issue as @antony on a project taking a very similar approach.  Given this plugin is fairly mature and only just over 200 lines of code, it was pretty straightforward to divide the pieces up ourselves: one plugin to decorate the request and another to define the schema and strategy to enforce on multiple connections.

**Comment by gordysc** [comment]
@jaw187 #152 should work for this case.  It's not leveraging a public API in Hapi 11.X.X, but should be safe.
