### ISSUE TITLE
Auth mode 'optional' does not distinguish between the lack of a session cookie and an invalid session cookie

### ISSUE THREAD

**Issue by dardyfella** [hapijs/hapi-auth-cookie#120]
I've noticed that when a route is configured with auth: { mode: 'optional' }, hapi-auth-cookie doesn't distinguish between the lack of a session cookie and an invalid session cookie.

For example, both of the following GET requests will return HTTP status code 200 and hit the route handler when ran against the example code [here](http://pastebin.com/nJ26UYZz):

`
curl http://127.0.0.1:8000/
curl http://127.0.0.1:8000/ -H 'Cookie: sid-example=badcookie'
`

Furthermore, if the / route is configured with plugins: { 'hapi-auth-cookie': { redirectTo: '/login' } } instead in the above example code, both of those GET requests will return HTTP status code 302 and get redirected to /login.

hapi-auth-cookie should reject requests with bad cookies when redirectTo is set to false and not redirect requests that have no cookies when redirectTo is set to a path-like string.

**Comment by jaw187** [comment]
@dardyfella Sorry for the delayed response.  `redirectTo` and `mode` are part of Hapi's core authentication strategy implementation.  I don't think there is anything that we could do without a change to Hapi core.  But I'll take a look.

**Comment by dardyfella** [comment]
@jaw187 No worries man. When I was looking around at the various hapi authentication plugins I found a similar request for [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2/issues/43)

**Comment by gordysc** [comment]
They apparently addressed this in a [PR](https://github.com/dwyl/hapi-auth-jwt2/pull/44).  I'll take a look at this tonight 👍

**Comment by sholladay** [comment]
You should try out my [PR #155](https://github.com/hapijs/hapi-auth-cookie/pull/155) as I believe it fixes all of your various concerns.

Since hapi core already handles the `mode` correctly, the solution is simply to respect it and delegate to hapi itself for the appropriate behavior.
