### ISSUE TITLE
Multiple server instances with catbox-redis

### ISSUE THREAD

**Issue by ugate** [hapijs/hapi-auth-cookie#122]
We're using [catbox-redis](https://github.com/hapijs/catbox-redis) in conjunction with `hapi-auth-cookie`. We have our system setup similar to the following:

![hapi](https://cloud.githubusercontent.com/assets/944948/14143735/d1b7cfa0-f65a-11e5-9913-c6e48c02cb30.png)

My question is how to manage sessions across `hapi` + `hapi-auth-cookie` + `catbox-redis` so that if a client hits any one of the `hapi` servers and has previously authenticated using `hapi-auth-cookie` subsequent requests to other `hapi` servers will recognize the client's cookie session ID that was previously stored in `Redis`. Our configuration is near identical to the example provided in this project with the addition of `catbox-redis`. The problem that we're having is that if request is made to another `hapi` server it immediately redirects to the login page before checking the cache. Is there a recommended way to handle this?

I tried to add an `onPreAuth` [extension point](http://hapijs.com/api#serverextevents):
```js
server.ext('onPreAuth', function chkCookieCache(req, reply) {
  if (req.auth.credentials || !req.route || !req.route.settings || 
      !req.route.settings.auth || !req.route.settings.auth.mode || 
      req.route.settings.auth.mode === 'try')
    return reply.continue();
  getSession(req, function chkCookieCacheCb(err, value) {
    if (!err && value && value.sid) req.cookieAuth.set({ sid: value.sid });
    reply.continue();
   });
});
function getSession(req, cb) {
  if (req.auth.credentials) return setImmediate(cb, null, req.auth.credentials);
  const sid = (req.auth && req.auth.credentials && req.auth.credentials.sid) || 
      (req.auth && req.auth.artifacts && req.auth.artifacts.sid) || 
      (copts && copts.cookie && req.state[copts.cookie] && req.state[copts.cookie].sid);
  if (sid) return cache.get(sid, cb);
  setImmediate(cb, new Error('Unable to determine session ID from request'));
}
```
...but I'm getting an error:
```js
[log,error], data: TypeError: Uncaught error: Cannot read property 'state' of undefined
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'state' of undefined
    at set (c:\nss\lawson-lbi-plus\node_modules\hapi-auth-cookie\lib\index.js:95:22)
    at chkCookieCacheCb (c:\nss\lawson-lbi-plus\server\server.js:141:68)
    at c:\nss\lawson-lbi-plus\node_modules\hapi\node_modules\hoek\lib\index.js:850:22
    at _combinedTickCallback (node.js:376:9)
    at process._tickDomainCallback (node.js:431:11)
```

**Comment by jaw187** [comment]
@ugate So sorry for the delayed response.  You should use the same cookie password on each Hapi server to ensure the cookies can be shared.

P.S. nice diagram!! :)

**Comment by ugate** [comment]
@jaw187 when you say cookie password are you referring to the `password` option [for the server state](http://hapijs.com/api#serverstatename-options)?
