### ISSUE TITLE
EPEERINVALID in hapi 13.3.0 version 

### ISSUE THREAD

**Issue by lutfor3737** [hapijs/hapi-auth-cookie#123]
I am trying to install this plugin.
npm install hapi-auth-cookie --save

Getting following error:
 
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/Lutfor/.nvm/versions/node/v4.4.3/bin/node" "/Users/Lutfor/.nvm/versions/node/v4.4.3/bin/npm" "install" "hapi-auth-cookie" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package hapi@13.3.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer good@6.6.0 wants hapi@>=8.x.x
npm ERR! peerinvalid Peer hapi-api-version@1.0.2 wants hapi@>=10.x.x
npm ERR! peerinvalid Peer hapi-auth-basic@4.1.0 wants hapi@>=10.x.x
npm ERR! peerinvalid Peer hapi-auth-cookie@6.1.1 wants hapi@>=11.x.x
npm ERR! peerinvalid Peer hapi-auth-bearer-token@4.1.0 wants hapi@>=8.x.x
npm ERR! peerinvalid Peer hapi-auth-jwt@4.0.0 wants hapi@>=10.x.x
npm ERR! peerinvalid Peer hapi-oauth2orize@1.3.0 wants hapi@^7.x.x
npm ERR! peerinvalid Peer hapi-swagger@4.3.1 wants hapi@^9.0.1 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Lutfor/Documents/TESTi/npm-debug.log

**Comment by Marsup** [comment]
It's all written in the error message.
hapi-oauth2orize only supports hapi 7. The master seems to have an unpublished 1.4 that fixes that.

/cc @devinivy

**Comment by lutfor3737** [comment]
Thanks @Marsup , uninstall hapi-oauth2orize. it's installed fine. But i need hapi-oauth2orize also.

**Comment by jaw187** [comment]
Thanks @Marsup
