### ISSUE TITLE
Simulate cookie authentication to run a Test

### ISSUE THREAD

**Issue by ralexrdz** [hapijs/hapi-auth-cookie#125]
I'm doing a test for all the functionalities of my system so when me or a collaborator develop a new functionality, we can be sure we didn't broke the rest. 

Since some funcionalities require cookie authentication to go through, and running [the test utility](https://github.com/hapijs/lab) doesn't store a cookie, I would like to ask you for the best practice to Simulate or include cookie authentication on this tests.

Thanks! ^^

**Comment by jaw187** [comment]
@relaxrdz

Your test should replicate the steps to obtain the proper cookie prior to testing the specific functionality you're interested in testing.

Often I find myself maintaining a file loaded with helper methods and use control flow to run these methods in succession prior to testing the desired functionality.
