### ISSUE TITLE
I can't set a cookie with domain redirection.

### ISSUE THREAD

**Issue by gragra100** [hapijs/hapi-auth-cookie#129]
Hi this is my code to set cookie:

```
server.register(require('hapi-auth-cookie'), function (err) {
    if (err) {
        console.error(err);
    }
    server.auth.strategy('session', 'cookie', {
        password: 'secret',
        cookie: 'sid',
        isHttpOnly: 'false',
        isSecure: false
    });
});
```

And into the log-in endpoint i use this function 
`request.cookieAuth.set(cookie);`

So i deployed this code in a remote server and then i connected to this server and i did log-in, all worked fine, but after that I bought a domain like "www.example.com" and I set the redirection on DNS in the domain's site, now if i connect to "www.example.com" and log in it the cookie is not setted. 
What can i do?

**Comment by jaw187** [comment]
@gragra100 Sorry for the delayed response.  I believe you just need to properly use the Domain property when setting up your auth scheme.
