### ISSUE TITLE
Allow users to override the cookie encoding

### ISSUE THREAD

**Issue by davidbarratt** [hapijs/hapi-auth-cookie#132]
I'm attemping to share cookies between a PHP application and a hapi application.

I thought I was going crazy in hapijs/statehood#22, but it looks like the problem is, is that this library has the session cookie hardcoded to use `iron`.

It would be really helpful if this library provided a way to specify the `encoding`.

**Comment by arb** [comment]
See https://github.com/hapijs/hapi-auth-cookie/issues/100 for pertinent discussion.

**Comment by davidbarratt** [comment]
wow. :(
