### ISSUE TITLE
third argument to the validateFunc's callback

### ISSUE THREAD

**Issue by paulovieira** [hapijs/hapi-auth-cookie#135]
This is what the documentation says about the 3rd  arg. to the callback:

_credentials - a credentials object passed back to the application in request.auth.credentials. If value is null or undefined, defaults to session. **If set, will override the current cookie as if request.cookieAuth.set() was called**._

But the action described in the bold doesn't seem to be happening. There's nothing in the plugin code that calls `reply.state` to update the cookie value. 

I haven't looked in the hapi core, but I did a quick test by updating the cookie data with the current timestamp on each request, and observed that the cookie is indeed always the same.

So either this is a bug / missing feature, or the docs should have that part removed.

**Comment by jaw187** [comment]
@paulovieira What's happening here is that the credentials object set in request.auth.credentials just for that individual request.  Perhaps the description needs to be more verbose.  But it's not actually changing the state.  It's JUST for the authenticated request.
