### ISSUE TITLE
Cookie not being set? 

### ISSUE THREAD

**Issue by PWAckerman** [hapijs/hapi-auth-cookie#143]
I have an API written with Hapi using hapi-auth-cookie that interacts with a few different front ends. I have isHttpOnly and isSecure turned on (API is only accessible through SSL/TLS). The login from my Ionic application (running on iOS), a Chrome Plugin, and even from POSTMAN work correctly, the cookie is set on the request object and I can verify its there before the request is sent (and I have an 'authed' endpoint to double check that the client has been authenticated correctly after the fact) and all subsequent requests are properly validated. However, when I try to login from a web application running in the Chrome browser (have not tried any other browsers), the cookie does not get set.

Part of the sequence for adding the cookie is this:

    request.cookieAuth.set({ sid: sid });
    console.log('set cookieAuth');
    console.log('request', request.headers);

so that I can inspect the headers once cookieAuth has been set. For all of the successful client-side applications, I can see the cookie as part of the headers when I do the logging after `cookieAuth.set` has been called. It will look something like: 

`cookie: 'sid=Fe26.2**e209400ebf6630d9d1f2d01d4ed5b49f116860cf8429d6ea244955087f3481f6*Tnp8Ou9BUGJcYqLxZEtsBQ*o_zXBoiNuwztdGockACNcRVllIs4pllAAKlKwXxeBn0**98506838190eb8c4f3b1989b530149f28f366db733fa75edf4fff4bca858928e*sJUjACyVv7CsEEkkHbx2ze1byRcJZ3ssyNk8Vz-ndwA'`

However, when I try to do authentication/authorization to the same `login` endpoint from the browser-based web application, with the same sequence of code, `cookie` is not even listed among the headers when I do the logging after `request.cookieAuth.set({ sid: sid });`. I can't understand why there would be different behavior.

**Comment by devinivy** [comment]
That header is a request header sent by the client.  Can you provide the response `set-cookie` header for the request during which cookies are set?  For a start, you might have an issue making AJAX calls without setting `withCredentials`, or hapi's new behavior (in v15) around using `SameSite` cookies by default might be causing you trouble.  Here are the v15 release notes for reference: https://github.com/hapijs/hapi/issues/3323

**Comment by PWAckerman** [comment]
If I log out the `request.response` object after the cookie has been set (request.cookieAuth.set), there does not seem to be any `set-cookie` header.

**Comment by PWAckerman** [comment]
`withCredentials` seemed to be the issue. The previous areas where I was doing cookie based authentication (Chrome Plugin & Ionic) previously were based at `file:///` rather than `http://` which seemingly allows Hapi to set the cookies without `withCredentials`. Now that I'm actually working with a real web application, `withCredentials` must now be required.
