### ISSUE TITLE
What is the best approach to prevent concurrent sessions for same user?

### ISSUE THREAD

**Issue by ravisuhag** [hapijs/hapi-auth-cookie#145]
What is the best approach if we want to restrict login from only one device/browser.

**Comment by turtleDev** [comment]
I'd imagine that you would need to keep track of currently authenticated users via a redis cache or a database.

**Comment by ravisuhag** [comment]
@jaw187 Any ideas other than storing it in the database and cross checking on every new login?

**Comment by ravisuhag** [comment]
For others who might need to do something similar. I implemented a time based super token in session and invalidate when needed in validateFunction.
