### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi-auth-cookie#153]
This module doesn't seem to be maintained any more, and could use a bit of TLC to fix outstanding issues and PRs. I got no answer when I asked about it in https://github.com/hapijs/hapi-auth-cookie/pull/142#issuecomment-261052175.

Per the hapi js [governance model](https://github.com/hapijs/contrib/blob/master/Governance.md#lead-maintainers), @jaw187 needs to communicate that he is still interested in the Lead maintainer role, otherwise we should find a replacement.

/cc @nlf as community lead.

**Comment by nlf** [comment]
i agree, this module is getting pretty stale. it would be good to see some movement here.

@jaw187 would you like to continue maintaining this? if not, let us know and we can start looking for someone to take it over.

**Comment by sholladay** [comment]
Another ping for @jaw187, just in case.

TLC is very much needed. https://github.com/hapijs/hapi-auth-cookie/issues/119 is a major bug - with an underwhelming title - that has existed for over a year. It makes this module basically unusable if the server has more than one connection. Every hacky workaround I have found leads to new problems. It's quite severe.

A fix has [been proposed](https://github.com/hapijs/hapi-auth-cookie/pull/152) with no response in 3 months.

There is even a [one-line documentation PR](https://github.com/hapijs/hapi-auth-cookie/pull/138/files) that has been sitting there for 8 months.

**Comment by jaw187** [comment]
@nlf It's probably best to find another maintainer.  I'm not using this plugin anywhere in any stack I maintain, so I probably do not find it to be as important as I should.

With that said, I'll get the current state of the project cleaned up to ensure a smooth transition.

**Comment by nlf** [comment]
Sounds good, thanks for getting back to us. I'll put the word out and we'll start looking for someone to take over!

**Comment by nlf** [comment]
Potential new maintainers --

If you're interested take a look at the current issues and pull requests, submit some fixes, leave some comments with your thoughts and opinions. If there are things you would like to change or add to the plugin, let's hear about them. Show some interest and activity and we'll consider you for the spot!

**Comment by gordysc** [comment]
While we're looking for a new contributor, can we push the latest as a release? There are some useful bits in the current code base my team would love to use.

**Comment by ChennyBaBy** [comment]
It would be really good to get the release a new version up, hoping use the `isSameSite` option 😄 .

**Comment by nlf** [comment]
version 7.0.0 was published by me while we continue to seek a new maintainer

**Comment by ChennyBaBy** [comment]
Woo Hoo 🎉 🎉 ! Thanks @nlf ~❤️ !

**Comment by mrlannigan** [comment]
@nlf I would like to maintain this project. I put in https://github.com/hapijs/hapi-auth-cookie/pull/174 to upgrade the module to hapi v17.

**Comment by mrlannigan** [comment]
I've begun maintaining this module.
