### ISSUE TITLE
Improve redirectTo behavior

### ISSUE THREAD

**Issue by sholladay** [hapijs/hapi-auth-cookie#154]
The `redirectTo` feature is great, but it is way too eager to activate and does not respect the `auth.mode` of routes.

From the docs:

> Note that using `redirectTo` with authentication mode `'try'` will cause the protected endpoint to always redirect, voiding `'try'` mode.

And also:

> `redirectOnTry` - if `false` and route authentication mode is `'try'`, authentication errors will not trigger a redirection. Requires hapi version 6.2.0 or newer. Defaults to `true`

This is all needlessly silly and complicated. I bet at least 95% of the time what people want is for `redirectTo` to only affect requests whose auth mode is `required`.

Currently I have to add this to every single route where auth is `optional`.

```js
plugins : {
    'hapi-auth-cookie' : {
        redirectTo : false
    }
}
```

I'm failing to think of a scenario where I _would_ want `redirectTo` and `optional` / `try` together. But if there is one, it is definitely not the common case.

I propose that `redirectTo` only triggers for `required` auth. We could have a `redirectOnTry: true` to re-enable the old behavior, but it's still a breaking change. And with the new behavior, I'm not sure anyone actually even needs the `redirectOnTry` option at all.

**Comment by jaw187** [comment]
@sholladay As noted in the PR, I worry about users that expect this behavior.  Since there is a flag to override the behavior, why should we eliminate it?

**Comment by sholladay** [comment]
> there is a flag to override the behavior

Nope. There is no flag that fixes the `redirectTo` shenanigans for `optional` mode. Are you going to introduce `redirectOnOptional` or just fix `redirectTo`? :/

**Comment by sholladay** [comment]
This was fixed in https://github.com/hapijs/hapi-auth-cookie/pull/186. 😃
