### ISSUE TITLE
Version on NPM is outdated

### ISSUE THREAD

**Issue by bf** [hapijs/hapi-auth-cookie#156]
I think this repo should be updated and a new version being pushed to NPM. Unfortunately I don't understand enough about cookies and hapi internals to take the role as maintainer :(

**Comment by gordysc** [comment]
@nlf @jaw187  I'm sure y'all are quite busy with a bunch of other things, but any chance we could get a new version published?

**Comment by bf** [comment]
I'm just using `"hapi-auth-cookie": "https://github.com/hapijs/hapi-auth-cookie",` in my `package.json` until the next breaking thing appears out of thin air on master :rofl:

**Comment by lironess** [comment]
really need that too because of "isSameSite" option

**Comment by gordysc** [comment]
@nlf @jaw187 Any chance of this happening soon? How can we help with this?

**Comment by nlf** [comment]
published 7.0.0
