### ISSUE TITLE
Add ability to pass the path option in cookieAuth.set(...)

### ISSUE THREAD

**Issue by JoshBarr** [hapijs/hapi-auth-cookie#158]
My use case is an application mounted at a path behind a reverse proxy. The path is only known to the app at runtime, so it would be neat to be able to pass in the cookie's path as an option, eg:

```js
request.cookieAuth.set(session, {data}, { path: request.headers['x-forwarded-path'] })
```

Happy to add this functionality in a PR if you are comfortable with the change :)

**Comment by mrlannigan** [comment]
Hi @JoshBarr and @tranan89 ,

If I understand your request correctly, you need the path of the cookie to be set to the forwarded host name received in the headers from the proxy in front of your hapi service? If so, I'm all for it. PR is more than welcomed.

**Comment by hueniverse** [comment]
Seems like this is no longer wanted since no one has submitted a PR. Feel free to open a new issue or PR with this enhancement.
