### ISSUE TITLE
auto-login

### ISSUE THREAD

**Issue by bounis** [hapijs/hapi-auth-cookie#160]
I need to authenticate without passing by login form by sending login and password in the URL like this:
[http://login:password@kibanaIp:5601](http://login:password@kibanaIp:5601).
is there any way to do that.
thnx.

**Comment by Marsup** [comment]
This is basic auth and you don't need cookies for that. See https://www.npmjs.com/package/hapi-auth-basic.

**Comment by becemwniss** [comment]
thank you for your response but i can't use basic auth  with custom login form so i was wondering if i can use basic auth and hapi auth aookie at the same time, means if i did not pass credentials in the url then the server reply redirect to the login form. 
thanks.

**Comment by wallacepeng** [comment]
hapi auth cookie does not support http basic auth header. In that case, you'd have to customize it.
