### ISSUE TITLE
Please, provide index.d.ts file in npm to simplify usage of hapi-auth-cookie in TypeScript

### ISSUE THREAD

**Issue by vguzev** [hapijs/hapi-auth-cookie#161]

**Comment by Marsup** [comment]
It's been asked a few times across the organization, won't happen, sorry.

**Comment by vguzev** [comment]
OK, as you wish... but keep in mind that enterprises are using Typescript nowadays. It's almost impossible to use "pure javascript" in huge projects...

**Comment by Marsup** [comment]
Typescript is still a minority and there are huge projects in pure javascript. Nice troll though...

That said, nothing keeps you from writing definitions, there's even a project dedicated to that, which I'm sure you know if you're actually doing typescript. Do you prefer us to do something we have no clue about or leave this to the typescript community ?

**Comment by Mutmatt** [comment]
@vguzev @Marsup I've taken a swing at the `index.d.ts`.

I would appreciate feedback from all involved. 

Please and thanks! 

[Mutmatt/DefinitelyTyped#hapi-auth-cookie](https://github.com/Mutmatt/DefinitelyTyped/tree/hapi-auth-cookie)
