### ISSUE TITLE
is there a way to disable easily?

### ISSUE THREAD

**Issue by walshe** [hapijs/hapi-auth-cookie#166]
Hi I need to do some load testing on my protected endpoints.. the process to populate a cookie is a bit complex so I would like to simply disable security so that I can load test the real logic in my endpoints without security.. is there a  tidy way to do this ?

**Comment by AdriVanHoudt** [comment]
But then you wouldn't test the performance of the security part? 
You could use `server.inject` and pass along a credentials object whereby hapi bypasses the security stuff...

**Comment by walshe** [comment]
wasn't worried about the security part.

no worries, luckily JMeter has a http cookie manager feature which allowed me to plug in a valid cookie for it to use, saving me having to tell it how to navigate the login process etc

thanks
E

**Comment by AdriVanHoudt** [comment]
No problem, glad you found a solution!
