### ISSUE TITLE
validateFunc session array?

### ISSUE THREAD

**Issue by Fjandin** [hapijs/hapi-auth-cookie#167]
Maybe this is more of a question than a bug?

Sometimes the validateFunc gives me an array of sessions instead of a single session object.

Bug or maybe some configuration issues on my side? or intentionally?

**Comment by dwelle** [comment]
This can happen if the client actually sends two, identically named (by default `sid`) auth cookies.

Does this happen to you in IE by any chance? IE ["leaks" cookies across domain/subdomains](https://stackoverflow.com/a/3567008/927631) which could be the cause.

**Comment by Fjandin** [comment]
It happened while using Postman actually

**Comment by dwelle** [comment]
there could be a bug in postman...

**Comment by Fjandin** [comment]
yeah. Probably is postman. I'll close this one as i don't see the issue anywhere else.
