### ISSUE TITLE
I get redirected to on an Auth route with 'optional' mode

### ISSUE THREAD

**Issue by Zedonboy** [hapijs/hapi-auth-cookie#171]
I have a route with mode 'optional',  but i made the property ```redirectTo = '/login'```  in auth config.

my problem, is when hapi hit that route, it get redirected to login route, hapi suppose to hit the handler, since its mode is "optional" or "try"

tell me what am getting wong.

**Comment by hellojeffhall** [comment]
I was wondering about this, too. It isn't mentioned in the README, but I think right now you have to add the following to your route config:

````node
plugins: { 'hapi-auth-cookie': { redirectTo: false } }
````

For example:

````node
{
  method : 'GET',
  path : '/optional',
  config : {
    handler : (request,reply) => reply('<h2>optional</h2>'),
    auth: { mode: 'optional' },
    plugins: { 'hapi-auth-cookie': { redirectTo: false } }
  }
},
````
Basically, the route's auth mode is being ignored when `redirectTo` is set. There is an open pull request [here](https://github.com/hapijs/hapi-auth-cookie/pull/155), as well as discussion [here](https://github.com/hapijs/hapi-auth-cookie/issues/154) and [here](https://github.com/hapijs/hapi-auth-cookie/issues/120) that go into a little more detail.

**Comment by Zedonboy** [comment]
Thanks,

**Comment by sreenu117** [comment]
Hello,
I am using hapijs server in kibana plugin. 
Problem I am facing is that the redirectTo is not working, I have already provided a handler and path to that handler is '/login'. Every time I am redirecting it to login through redirectTo it is showing error:{"statusCode":404,"error":"Not Found","message":"Not Found"}.
Please help me regarding this.

**Comment by Zedonboy** [comment]
Hello,  Rulr of thumb computer/hapi can never be wrong,  almost all errors
are from the programmers themselves.

Check your routes.  redirectTo makes a GET request,  so check your handlers
HTTP methods

**Comment by Marsup** [comment]
On another note, please don't hijack the 1st random issue you find, create your own, it's unmanageable otherwise.
