### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-cookie#172]

**Comment by vinicius0026** [comment]
I'm thinking on landing a PR for this. I would do it in 2 steps, first I would update all dependencies to latest versions, except for hapi, and fix tests that will break with latest lab version.
Then I would proceed to update the module itself, and hapi to v17.
It will be my first attempt to contribute to hapi ecosystem. I have been using many of the packages around hapi, including this one, and I have a decent understanding of this module from a user point of view. But I might need some help and a dedicated reviewer would be much appreciated.
What do you think? @hueniverse @nlf

**Comment by hueniverse** [comment]
@vinicius0026 go for it. I don't think @jaw187 is still actively maintaining it.

**Comment by reesmanp** [comment]
How's this going?

**Comment by mrlannigan** [comment]
Version 8.0.0 has been released.
