### ISSUE TITLE
New Lead Maintainer

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-cookie#175]
@jaw187 Looks like you are no longer maintaining this module. Any objections to passing it to someone else?

**Comment by Marsup** [comment]
He was not against the idea in #153.

**Comment by hueniverse** [comment]
WFM

**Comment by hueniverse** [comment]
@mrlannigan do you want to take over as lead maintainer?

**Comment by mrlannigan** [comment]
Sounds good to me.

**Comment by hueniverse** [comment]
@mrlannigan you are all set. Good luck!

**Comment by hueniverse** [comment]
@mrlannigan you signed on to be the lead maintainer but the module is still in dire need of attention. Are you still interested in the role or should we look for a new lead?

**Comment by mrlannigan** [comment]
Versions 7.1.0 (for hapi 16, specifically for #151) and 9.0.0 have been released.
