### ISSUE TITLE
Cookie is not being setted

### ISSUE THREAD

**Issue by mattonit** [hapijs/hapi-auth-cookie#177]
I'm using Hapi 16 with hapi-auth-cookie 7. The problem is that the following code does not set the cookie:
`request.cookieAuth.set({ foo: baz });`

`isAuthenticated` returns false, `request.auth.credentials` returns undefined

Any ideas, guys?

**Comment by marpstar** [comment]
@mattonit -- if you're running locally, you may need to set the `isSecure` option to `false`. That worked for me.

**Comment by marcuspoehls** [comment]
@mattonit Did you solve the problem? If it’s related to the `isSecure` option, this 1-minute video on [secure your hapi cookies in production](https://www.youtube.com/watch?v=6m2XeSYfINg) might help.
