### ISSUE TITLE
Can I disable encryption for a simple SID?

### ISSUE THREAD

**Issue by jtlapp** [hapijs/hapi-auth-cookie#178]
If I'm only using a session ID with no extra data, encrypting it doesn't buy me anything. Is there a way to turn off encryption? I'd rather not waste the clock cycles if I don't have to.

I'll be storing session ID hashes on the server, no keys. That way should someone breach the server, they'll be forced to muck with the server and risk detection and not also have the option of silently spoofing users of their choosing.

I'll be happy to trust keys when I can keep them in an HSM. Thanks!

**Comment by Marsup** [comment]
Unlikely to happen considering #100.

**Comment by jtlapp** [comment]
Thanks for pointing me to that conversation. I also don't need the expense of conversion to and from JSON. I'll look elsewhere.
