### ISSUE TITLE
identifying code

### ISSUE THREAD

**Issue by Tancy4hw** [hapijs/hapi-auth-cookie#181]
I wander if there is some identifying code plugin for hapi-auth-cookie.

I'm using nd-bmp, the identifying pic was recognized as unauthenticated request and blocked. Is there anysolutions?

**Comment by mrlannigan** [comment]
Hello @Tancy4hw,

I'm not entirely sure what you are asking. What do you mean when you say "identifying code plugin". And can you provide a link to the "nd-bmp" library, for I was unable to find any useful information given the context I have at this point.

**Comment by mtharrison** [comment]
Captcha verification or similar would be part of the login process, for example after validating username/password from a form, you would also validate the code, and then if successful you would set the auth cookie (`request.cookieAuth.set(...)`). The implementation/verification of the code itself is not within the scope of this plugin.

**Comment by Tancy4hw** [comment]
The total verification solution would be like you said, @mtharrison .

My problem was the verification code pic generated by gd-bmp which placed at server can not reply to the front end before validation.  it's solved using a filter. 
![image](https://user-images.githubusercontent.com/29646812/34186329-e2acdd7c-e565-11e7-982c-f4f4e7f5911f.png)
And my login page is like below:
![login](https://user-images.githubusercontent.com/29646812/34186831-ffa9b0dc-e568-11e7-9db1-84d3b35b04e5.JPG)
