### ISSUE TITLE
unable to register hapi-auth-cookie in node js hapi js application

### ISSUE THREAD

**Issue by sasidhar-movva** [hapijs/hapi-auth-cookie#184]
I am trying to register hapi auth cookie in my node js hapi js application. I am able to register inert and bell packages but while registering Hapi auth cookie it is throwing an error. hapi-auth-cookie throws an error [1] "attributes" is required while registering

[Link for code repository](https://github.com/SaurabhLpRocks/ng2-node-oAuth-demo)

![image](https://user-images.githubusercontent.com/33686271/34554459-fe126af2-f152-11e7-9b5c-287469bdb507.png)

```
import * as AuthCookie from 'hapi-auth-cookie';
import * as Bell from 'bell';

export function init(configs: IServerConfigurations, database: IDatabase): 
Promise<Hapi.Server> {
    const oauthConfiguration = OAuthConfiguration.getOAuthConfigs();

    return new Promise<Hapi.Server>(resolve => {


        //  Setup Hapi Plugins
        const plugins: string[] = configs.plugins;
        const pluginOptions = {
            database,
            serverConfigs: configs
        };

        const attribute = {
            name: 'authentication',
            version: '1.0.0'
        };


        const authCookieOptions = {
            password: 'cookie-encryption-password', 
            cookie: 'my-auth', // Name of cookie to set
            redirectTo: '/login',
            isSecure: false,
        };

        const pluginPromises = [];

        pluginPromises.push(server.register(Inert));
        pluginPromises.push(server.register(Bell));
        //getting error while registering auth cookie
        pluginPromises.push(server.register(AuthCookie)); 


    });
}
```

**Comment by SkaterDad** [comment]
@sasidhar-movva I believe you are having issues because `hapi-auto-cookie` version 8+ is intended to be used with `hapi` version 17+ (which changed how plugins are registered).

If you need to use `hapi` v16.x like in your repo, you will need to install an older version of `hapi-auth-cookie`.
