### ISSUE TITLE
cookieAuth.ttl not overwriting keepAlive ttl

### ISSUE THREAD

**Issue by antoniosanmartin** [hapijs/hapi-auth-cookie#187]
I am using the plugin for an API REST using hapi 16.6.2 and hapi-auth-cookie 7.0.0. I set the keepAlive : true in the plugin initialization. In the login controller I have a "remember me" parameter which sets the ttl (request.cookieAuth.ttl) for 15 days. This is not posible as the keepAlive function overwrites with the default ttl. ¿Am I missing something? ¿Is not the right approach for a remember me?

**Comment by raxell** [comment]
Late response but hope can be useful to others facing this issue.

You can use the [lifecycle events](https://hapijs.com/api#lifecycle-workflow) to workaround the issue.
In the login handler store the ttl in the cookie, then listen to `onCredentials` to update the ttl overridden by keepAlive.
Something like this:
```javascript
server.ext('onCredentials', (req, h) => {

    const session = req.state.sid;

    if (session) {
        req.cookieAuth.ttl(session.ttl);
    }

    return h.continue;
});

server.route({
    method: 'POST',
    path: '/login',
    // other options ...
    handler(req, h) {

        // your login logic ...

        req.cookieAuth.set(userData);

        if (req.payload.rememberMe) {
            const rememberMeTtl = 15 * 24 * 60 * 60; // 15 days
            req.cookieAuth.set('ttl', rememberMeTtl);
            req.cookieAuth.ttl(rememberMeTtl);
        }
    }
});
```
