### ISSUE TITLE
What is the best way to write controller tests?

### ISSUE THREAD

**Issue by createthis** [hapijs/hapi-auth-cookie#188]
I apologize if this is obvious, but I'm having trouble figuring it out.

What is the best way to write controller tests for an end point protected by hapi-auth-cookie?

I'm doing something like this in my controller test:

```javascript
      let response = await server.inject(request);
      should.equal(response.statusCode, 200);
```

However, request.url is protected by hapi-auth-cookie, so I get a 302 redirect code because it (correctly) wants me to log in.

What's the best way to fake a login so server.inject works as expected?

**Comment by Marsup** [comment]
`server.inject` contains a `credentials` option to provide your own, it's all in the docs of hapi.

**Comment by createthis** [comment]
That worked very well. Thank you, @Marsup.
