### ISSUE TITLE
isSameSite no longer respects server level setting

### ISSUE THREAD

**Issue by travi** [hapijs/hapi-auth-cookie#190]
after rebasing the branch for https://github.com/hapijs/hapi-auth-cookie/pull/151 last night, i found one of the apps that was using that branch broken this morning. 

the breakage was related to that app needing `isSameSite` to be set to `Lax` for its particular use case. the app had that [configured at the server level](https://hapijs.com/api/16.6.2#serverstatename-options), but not as a direct option to the `hapi-auth-cookie` plugin (because my fork was from before it was [available as a direct plugin option](https://github.com/hapijs/hapi-auth-cookie/commit/4368d97bc1fc311f5636fa485020e8cdef0a0ff2)).

[the change](https://github.com/hapijs/hapi-auth-cookie/commit/4368d97bc1fc311f5636fa485020e8cdef0a0ff2) that got pulled forward when i rebased my branch defined a [default value of `Strict`](https://github.com/hapijs/hapi-auth-cookie/blob/4368d97bc1fc311f5636fa485020e8cdef0a0ff2/lib/index.js#L33) for `isSameSite` at the plugin level, which is a very logical default (especially since it matches the [server-level default](https://hapijs.com/api/16.6.2#serverstatename-options)). however, it ends up overriding the setting from the server level by being so forceful in setting that default value. 

i found this to be unexpected. i would have expected that `hapi-auth-cookie` would honor the `isSameSite` value from the server-level config, if provided. in my case, i'm fine to just move this config from server-level to plugin-level since this is the only cookie set by this app. in the more general case, though, this seems like unintended behavior. 

is this overriding default value intended behavior?

**Comment by hueniverse** [comment]
Replaced by #207
