### ISSUE TITLE
Breaking docs

### ISSUE THREAD

**Issue by acmoune** [hapijs/hapi-auth-cookie#192]
I am still using v6.1.1, I will not migrate to hapi@17 soon, I will really appreciate if you can give me a link to the previous docs. I am actually confused with the signature of the validateFunc callback, now everything is `async await ...`

I think you should do it for all plugins broken by hapi@17, leave a link to the previous docs.

Thanks.

**Comment by devinivy** [comment]
To unblock you you can always do this,
1. Navigate to https://github.com/hapijs/hapi-auth-cookie/releases
2. Find the relevant version of the package
3. Click the commit hash underneath the relevant version
4. Click "Browse Code"
5. Find the docs for your version :)

**Comment by acmoune** [comment]
ok, Thanks @devinivy
