### ISSUE TITLE
sessions don't survive server restart

### ISSUE THREAD

**Issue by sscarduzio** [hapijs/hapi-auth-cookie#200]
It's my understanding from the documentation that if I run the example code with the hardcoded password 'password-should-be-32-characters', this will be the decryption key of the cookie. Therefore, after I logged in, even if restart the server, I should be able to refresh the browser and still have a valid session. 

This does not happen. Why? And how can I make hapi-auth-cookie behave like this?

I'm trying to achieve this behaviour in order to be able to run N servers behind a load balancer, without the need of sticky sessions.

Thank you for the great module!

**Comment by ebertmi** [comment]
@sscarduzio even if you have a valid session ID the server is not aware of the ID. During restart your in-memory-cache gets flushed / destroyed and therefore the information is not there anymore. You can configure for example some redis cache to persist the data.

**Comment by mrlannigan** [comment]
Mark for closure.

**Comment by sholladay** [comment]
I can't reproduce this. I'd be willing to work on it if you can provide a failing test case, as we rely on the session continuing after a server restart.

My best guess is that you might have `clearInvalid` set to true and something is causing your cookie to be considered invalid. Could be `validateFunc` if you are also using that.
