### ISSUE TITLE
10.0.0 Release notes

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi-auth-cookie#209]
- Requires hapi v18
- Removes `ignoreIfDecorated` option
- Moves cookie options:
  - `cookie` - to `cookie.name`
  - `strictHeader`, `isSecure`, `isHttpOnly`, `isSameSite`, `path`, `domain`, `ttl`, `password` - into `cookie`
- Uses server state defaults instead of module defaults
- `path` default changed from `/` to `null` (no path)

**Comment by kanongil** [comment]
`clearInvalid` is missing from the list of moved cookie options.
