### ISSUE TITLE
Refreshing sessions from AJAX calls

### ISSUE THREAD

**Issue by danidacila** [hapijs/hapi-auth-cookie#50]
Hi guys,

I encountered a problem.
I have a web app composed of JS front + NodeJS API backend.
I use hapi + auth-cookie for sessions on the backend.
All of the frontend interaction is done with the content through AJAX API calls.
Some of these calls update data that is also present in the session.
For example it changes the user email, user being stored in the session.

I wrote code to refresh the session, but to my amazement it was not working.
After 1 day of thinking it over and over I think it has to do with the fact that all calls were AJAX and therefore the browser was not updating the session cookie.

I changed then the implementation of the hapi-auth-cookie to use a server side cache for storing the session data and in the cookie there is the sessionId.
This way my session gets refreshed correctly.

I am curious if you are interested in making this part of the plugin?

Thanks,
Daniel

**Comment by hueniverse** [comment]
You don't need to change the implementation, you just need to store the right data set in the session and lookup the rest in the server storage. However, I don't understand why the browser failed to update the cookies. It should not matter how the request was made.

**Comment by danidacila** [comment]
Yes you are right, I can store the cache outside of the implementation and use it.
Also reading more about AJAX cookies it seems they are sent and received back withing the calls.
But for sure it was not working for me setting any new key in the session or updating it.

And one more question I have is if I change the session data, it means the session cookie will be changed, right? As it represents an encoded version of the session data?

Tx,
Daniel

**Comment by jaw187** [comment]
@danidacila are you taking additional steps to retrieve the cookie from your Ajax response?  If you're expecting them to show up in `document.cookie`, that won't happen.

To answer your latest question, every call to `request.auth.session.set` will result in a call to `reply.state` which will update the cookie.

**Comment by technowar** [comment]
@jaw187, may I ask why cookies set by `hapi-auth-cookie` won't appear in `document.cookie`? How can I handle my cookie if this is the case?

**Comment by hueniverse** [comment]
The cookie is encrypted so it won't help you much getting it in the browser.

**Comment by jaw187** [comment]
@technowar `document.cookie` is set when the initial page is loaded.  Ajax requests from scripts do not set `document.cookie`.  But the browser will store the cookie accordingly and use it for subsequent requests.

**Comment by technowar** [comment]
Thanks all. I thought I got it all wrong.
