### ISSUE TITLE
Are there plans for Flash messages support?

### ISSUE THREAD

**Issue by gansbrest** [hapijs/hapi-auth-cookie#51]
Something similar to flash(type, message, isOverride) in Yar ? I think it's pretty common for websites to have the option to display some kind of one time messages 'error', 'success', 'warning' and it seem to have this wrapper method in the plugin for convenient use in request handlers. Or maybe there is better way to store one time sitewide messages?

**Comment by hueniverse** [comment]
I would be against it. It is bad security practice to mix authentication with application layer data. You should use cookie auth together with yar, each for its own purpose.

**Comment by gansbrest** [comment]
Hm, for some reason I thought Yar and Hapi-auth-cookie to be competing projects, since they both deal with sessions. Now thanks to your response I noticed that Yar doesn't deal with auth strategies and schemes.
