### ISSUE TITLE
How can I set multiple session cookies with different names?

### ISSUE THREAD

**Issue by gansbrest** [hapijs/hapi-auth-cookie#52]
Here is my use case. I'm building new frontend app for our legacy website. Temporarily I need to provide a flow where user logs in through my new app and I set 2 cookies, one for the new app session, and one for the legacy site ( written in PHP ).

Basically I'm trying to find a way how to set new session cookie ( or a cookie with custom name and value and not protected by Iron ) so our legacy app could read it, in addition to standard session cookie provided by hapi-auth-cookie.

Maybe it's not 100% related to this plugin, but I hope you can point me to the right direction...

**Comment by jaw187** [comment]
Use the `state` method in the response object to set another cookie.  http://hapijs.com/api#response-object

Make sure to pass the appropriate cookie options so it works with your legacy app.
