### ISSUE TITLE
How to set session when I am using socket.io for authenticating user

### ISSUE THREAD

**Issue by KaustubhYK** [hapijs/hapi-auth-cookie#54]
Hello,
I am using socket.io to get username and password from user and after validating username and password I want to set session for him.

**Comment by jaw187** [comment]
I believe that the Socket.IO request object should come from Hapi and will provide you with the ability to call `socket.request.session.set`.  But I can't verify.  Please test and let me know if you have success.

**Comment by KaustubhYK** [comment]
I tried both socket.request.session and socket.request.auth to set session,but both are undefined.

**Comment by jaw187** [comment]
I'll keep this open till I test it out.  I do have some concerns about using an existing unauthenticated request/socket, performing authentication, and continuing to use that same socket.

**Comment by grabbou** [comment]
Check out passport socket.io extension which servers the same functionality in express.js world. Been using it for a while before switching to Hapi and was working flawlessly.

**Comment by sibartlett** [comment]
I've written a socket.io plugin for hapi called [hapi-io](https://github.com/sibartlett/hapi-io), that allows you to authorize a socket.io connection using an existing hapi cookie session (amongst other things). As @jaw187 said, it's probably best to authenticate the user before creating a socket.io connection.

**Comment by jaw187** [comment]
:+1:
