### ISSUE TITLE
accessing auth, without fully blocking the endpoint

### ISSUE THREAD

**Issue by rutaihwa** [hapijs/hapi-auth-cookie#57]
I would like to understand how to access auth to an end point even though its not required that one would have been authenticated, in a way, offer a different views according to authenticated users.
Simple example, `/register` if one is authenticated skip, if not show the form. My problem is if i use `auth: 'stategy'`, everyone get redirected to `/redirectURI` with next `register` which is not what i want.

**Comment by hueniverse** [comment]
You can use auth mode `'try'`

**Comment by rutaihwa** [comment]
Thanks @hueniverse , it works! with route plugin option redirectTo: false.
