### ISSUE TITLE
Unable to set cookie to browser session for a specific request

### ISSUE THREAD

**Issue by briandela** [hapijs/hapi-auth-cookie#59]
We have a default hapi-auth-cookie expiration of 2 weeks. However, for some users we want to allow them to set the auth cookie to be browser session only (e.g. unchecking a `remember me` checkbox on the login form).

e.g. plugin config
```js
options: {
    password: process.env.AUTH_COOKIE_PWD,
    ttl: moment.duration(2, 'weeks').asMilliseconds(),
    domain: process.env.AUTH_COOKIE_DOMAIN,
    redirectUrl: '/login'
}
```

During the request we have something like this:

```js
if(!remember) {
    request.auth.session.ttl(null);
}
```

However, this will still result in the ttl being set to `moment.duration(2, 'weeks').asMilliseconds(),`. It looks like `statehood` will always take the base options when the ttl is set to null: `var definition = cookie.options ? Hoek.applyToDefaults(base, cookie.options) : base;` (https://github.com/hapijs/statehood/blob/4fdaea4677c147e61175ad7ded4fa54dd1125dd7/lib/index.js#L354)

This makes sense from the `statehood` perspective, but from the `hapi-auth-cookie` perspective my expectation as a user would be that calling `request.auth.session.ttl()` would override the ttl set in default options - this only appears to be the case some of the time (for non-null values)

We can work around this on our side by defaulting everything to browser session and inverting our logic to explicitly set the ttl using this following:

```js
if(remember === true) {
    request.auth.session.ttl(moment.duration(2, 'weeks').asMilliseconds());
}
```

However, this now means our main-line scenario (people leaving the box checked) has it's ttl separated from the hapi-auth-cookie plugin config.

Wanted to open this issue to see if there is a solution to have `request.auth.session.ttl(null);` work or if the `hapi-auth-cookie` docs should be updated to point out this scenario.

**Comment by jaw187** [comment]
This is because of how `applyToDefaults` works.  Opened issue in `hoek`

**Comment by jaw187** [comment]
https://github.com/hapijs/hoek/pull/140 contains a change that will allow us to fix this.

**Comment by jaw187** [comment]
@briandela Hoek 2.13.0 contains an enhancement where `applyToDefaults` will take a `isNullOverride` flag.  Feel free to put together a PR which turns this feature on, if not, I should get to it tomorrow.

**Comment by briandela** [comment]
@jaw187 Thanks for the heads-up. I'm not able to submit a PR at the moment but I probably will be able to this weekend.

**Comment by jaw187** [comment]
Totally forgot that the change isn't in `hapi-auth-cookie`, rather it's in `statehood`.  Opened https://github.com/hapijs/statehood/pull/12

**Comment by jaw187** [comment]
@briandela Statehood 2.1.1 contains the update that should fix your issue.  Go ahead and test, let me know if anything else comes up.

**Comment by jaw187** [comment]
@briandela Go ahead and reopen this if there is still an issue
