### ISSUE TITLE
Session is not being set in FX 39 and Chrome 43

### ISSUE THREAD

**Issue by cadecairos** [hapijs/hapi-auth-cookie#60]
These dev browsers (FX 39 and Chrome 43) appear to be unable (or unwilling?) to set a session cookie generated by hapi-auth-cookie.

Here's my reduced test case: https://gist.github.com/cadecairos/5bcfa6aeba06c2c69952

**Comment by jaw187** [comment]
I can't think of anything special which `hapi-auth-cookie` is doing to set the cookie which would introduce this problem.  Can you test cookies from other applications/sites using the dev browsers?

**Comment by cadecairos** [comment]
I use Firefox developer edition as my daily driver,  and haven't seen anything like this. I also checked that express session cookies properly get set on localhost in both dev versions.

**Comment by jaw187** [comment]
Have you tested setting a cookie through a traditional request instead of using an Ajax request?  In the end, this issue will most likely be moved to https://github.com/hapijs/statehood

**Comment by cadecairos** [comment]
I'll give that a try next time I'm at my computer.

**Comment by cadecairos** [comment]
Turns out this was a bug with the polyfill of fetch setting withCredentials to true by default, and me not providing the `credentials` mode option to fetch. It broke in Firefox and Chrome Dev versions because they have the fetch API implemented.

**Comment by jaw187** [comment]
:+1:
