### ISSUE TITLE
domain is now required as a string, and null does not pass validation

### ISSUE THREAD

**Issue by mshick** [hapijs/hapi-auth-cookie#64]
Hapi's server.state accepts `domain: null` as an option, and this is a useful setting for me when in active development, because devs all use different local domains.

I think schema validation should be updated, and the logic [here](https://github.com/hapijs/hapi-auth-cookie/blob/master/lib/index.js#L60-L63) adapted to check property presence, not truthiness:

```js
if (settings.hasOwnProperty('domain')) {
  cookieOptions.domain = settings.domain;
}
```

**Comment by jaw187** [comment]
If `domain` is omitted from options, it will default to `null` via https://github.com/hapijs/statehood/blob/master/lib/index.js#L47

**Comment by mshick** [comment]
Okay, fair enough. Similar to `redirectTo` I would like the ability to explicitly set a null value. request / enhancement seems right. Feel free to close it (and the PR) if you're not interested.

**Comment by jaw187** [comment]
Version 2.2.0 has the update for this

**Comment by mshick** [comment]
Great, thanks!
