### ISSUE TITLE
how do I access the cookie after it is validated?

### ISSUE THREAD

**Issue by paOol** [hapijs/hapi-auth-cookie#70]
My code pretty much looks very similar to this repo.
https://github.com/santbob/hapi-auth-example

my request.auth object is
```
{ account:
   { provider: 'instagram',
     token: ' ',
     query: {},
     profile:
      { id: ' ',
        username: ' ',
        displayName: ' ',
        raw: [Object] } } }
{ isAuthenticated: true,
  credentials:
   { provider: 'instagram',
     token: ' ',
     query: {},
     profile:
      { id: ' ',
        username: ' ',
        displayName: ' ',
        raw: [Object] } },
  artifacts: { sid: ' ' },
  session: { set: [Function], clear: [Function], ttl: [Function] },
  mode: 'try',
  strategy: 'session' }
```

In one of my handlers, I tried 
```
    if (request.auth.isAuthenticated)
```
and it did not pass.

How/where do I access the cookie so I can check if a user is authenticated in other parts of my app?

**Comment by jaw187** [comment]
You do not need to validate the cookie if the other parts of your app are running on Hapi.  If your routes have the hapi-auth-cookie authentication scheme applied, then you can know that your code will only be accessed when the user is authenticated.

If you need any information about the user which you set via`request.session.state`, it can be retrieved from `request.auth.credentials`
