### ISSUE TITLE
validateFunc doc

### ISSUE THREAD

**Issue by jardakotesovec** [hapijs/hapi-auth-cookie#71]
Hi,
got confused by following docs for `validateFunc`

> credentials - a credentials object passed back to the application in request.auth.credentials. If value is null or undefined, defaults to session. If set, will override the current cookie as if request.auth.session.set() was called.

Because source code [suggests](https://github.com/hapijs/hapi-auth-cookie/blob/master/lib/index.js#L145) that cookie just get updated by `session` object, not `credentials` object. And it gets updated only if `keepAlive` is true.

**Comment by jaw187** [comment]
An authenticated route will be able to access the `credentials` object via `request.auth.credentials`.

**Comment by jardakotesovec** [comment]
Thanks for answer. 

I understand that part, my confusion is about the latter part:

> If set, will override the current cookie as if request.auth.session.set() was called.

That would suggest that If `credentials` are set, it will override the cookie with new content - which does not seem to be true in the code.

**Comment by jaw187** [comment]
It doesn't set the cookie, it overrides the value used when the application sets `request.auth.credentials`.  If `credentials` is `null` or `undefined`, the application will use the cookie when setting `request.auth.credentials`.
