### ISSUE TITLE
Keep pathname or headers after redirectTo

### ISSUE THREAD

**Issue by edravis** [hapijs/hapi-auth-cookie#73]
So, my case:

If you access directly to an url which needs some auth and  your aren't logged. I cannot get the refer url because I've been redirected. For example:

A. Access to domain.com/private
B. Because isn't logged it's redirected to domain.com/auth/signin
C. In the handlers now there's the data of /auth/signin not /private

I hope I've explained myself well enough. Maybe I'm thinking in a bad way and I shouldn't check the refer url like that, but this will be possible using Hapi? Or is planned? Or something?

Thanks

**Comment by jaw187** [comment]
I see what you're saying.  Not sure what the solution is, let me stir on it and get back to you.

**Comment by hueniverse** [comment]
Other than referer header, do you need anything else?

**Comment by edravis** [comment]
I guess no. The important for me is being able to access to the original url. I can find it in the referral header.

**Comment by jaw187** [comment]
@edravis Ok to close?  Keep in mind that you'll have to pass the referrer along with the credentials to the route that validates the credentials.

**Comment by edravis** [comment]
@jaw187 Just like how I thought it should be :grin:
