### ISSUE TITLE
How to implement redirectUrl after authentication?

### ISSUE THREAD

**Issue by rainabba** [hapijs/hapi-auth-cookie#76]
I'm actually using Bell and hapi-auth-cookie and I'm not sure which (or both) plugins would need to be involved since I don't quite understand yet how they interact, but I need to be able to send someone to a route to initiate auth and after they're successfully authenticated, redirect them to that URL.

It seems like this is a standard part of the OAUTH process, or at least once was, but I'm wondering if these plugins use that functionality and thus need to provide it themselves to effectively bring it back.

I'm trying to build a plugin to ease the use of bell and hapi-auth-cookie [hapi-bell-cookie-auth-plugin](https://github.com/rainabba/hapi-bell-cookie-auth-plugin), but just today I found another doing something similar [https://github.com/hofan41/clapper](https://github.com/hofan41/clapper) and even more nicely written (though mine is very fresh in my defense).

I'm going to post this in Bell also and will close on either side if/when it's clear that it's a one-sided issue.

**Comment by hueniverse** [comment]
I have no idea what you are asking for.

**Comment by rainabba** [comment]
Sorry, the key point there was, "I need to be able to send someone to a route to initiate auth and after they're successfully authenticated, redirect them to that URL."

- User navigates to /auth/twitter?ReturnUrl=/foobar (no session yet exists so I can't persist the ReturnUrl value for the final redirect).
- User is sent to twitter auth and redirected to my app
- My app confirms and sets up a session then redirects the user (here I'd like to redirect using ReturnUrl)

Right now, I can control the final redirect, but if I put an auth strategy (using Bell) on a route, I cannot find any way to capture the ReturnUrl, then persist it in a way that can be retrieved (unique that that logical session) later.

**Comment by hueniverse** [comment]
You can use **yar** for that. Basically using it as unauthenticated session management.

**Comment by rainabba** [comment]
Seems that even with yar, the core issue exists, how to get and persist the ReturnUrl. The only place I can find to obtain it before Bell/hapi-auth-cookie take over is onRequest, but when I try the following, I get an a 500/internal error with no additional details (though admittedly maybe I just don't know how to get more than what is provided in the err object in the internalError handler.

```
    request.session.set('returnUrl', {
      key: request.query.ReturnUrl
    });
```

I'm implementing yar with
```
        {
            register: require('yar'),
            options: {
                cookieOptions: {
                    password: 'foobar'
                }
            }
        }
```

**Comment by hueniverse** [comment]
This is what I do in postmile: https://github.com/hueniverse/postmile-web/blob/master/lib/login.js#L15-L31

You need to preserve the original URI somewhere so you can fetch in after successful bell auth and redirect there.

**Comment by rainabba** [comment]
Thank you. Finally got things working and yar was the key.
