### ISSUE TITLE
Redirect only when authenticated is required

### ISSUE THREAD

**Issue by SevereOverfl0w** [hapijs/hapi-auth-cookie#77]
I'm trying to figure out how I can redirect a user to `/login?next=/protected` only when authentication is required on a route.

For example, `/` should be public & accessible to anybody.
But when going to `/protected` & not logged in, you should be redirected to the route above.

I tried implementing this myself with `onPreAuth` but as I can't detect if a user is authenticated yet, it's not possible there. `onPostAuth` doesn't work either, as it has already redirected the request if it's not authenticated.

**Comment by jaw187** [comment]
If you don't want authentication applied to a route, do not include auth settings in your route config.

**Comment by SevereOverfl0w** [comment]
I'd like authentication to be optionally available in the route, so that I can provide user-centric information (e.g. hide/show login/logout information in the output)

**Comment by Marsup** [comment]
Why aren't you using optional or try mode ?

**Comment by SevereOverfl0w** [comment]
I am using optional mode, but the redirect is still applied in optional mode.

**Comment by Marsup** [comment]
Did you set the redirectOnTry option ?

**Comment by SevereOverfl0w** [comment]
I left it as default (true)

**Comment by SevereOverfl0w** [comment]
I set redirectOnTry to false, and still redirects were taking place.

**Comment by hueniverse** [comment]
@SevereOverfl0w did you use `try` mode with the `redirectOnTry` set to false? that's exactly what it is for.

**Comment by SevereOverfl0w** [comment]
Ah, derp. Given the similarities between `try` and `optional`, should it prevent redirects on both?

**Comment by hueniverse** [comment]
No. They are different modes.

**Comment by SevereOverfl0w** [comment]
redirectOnOptional might be somewhat appropriate though? They have similar use cases don't they? Just that one is okay with invalid (corrupted?) authentication. Or have I misunderstood the difference?

**Comment by hueniverse** [comment]
You should be able to accomplish the same result with try.
