### ISSUE TITLE
Buffer type should be allowed for "password" option

### ISSUE THREAD

**Issue by kanongil** [hapijs/hapi-auth-cookie#80]
I supply a node `Buffer` as the argument to the password option. However this broke in 2.2.0 and I get the following error:

```js
ValidationError: child "password" fails because ["password" must be a string]
```

**Comment by jaw187** [comment]
The easiest thing that you could do is convert the buffer to a string, otherwise https://github.com/hapijs/hapi-auth-cookie/blob/master/lib/index.js#L25 needs to be updated to allow the a Buffer.

**Comment by hueniverse** [comment]
We should allow passing a buffer.
