### ISSUE TITLE
Example demonstrating proper use of set(key, value)

### ISSUE THREAD

**Issue by rainabba** [hapijs/hapi-auth-cookie#86]
Calling it without error is simple enough, but I can't find (even right after the call) where I actually retrieve the value.

I expect `request.auth.session.set('someData', { foo: 'bar' });` to be accessible with `request.auth.session.someData`.

An example showing the correct way(s) to use this would be greatly appreciated.

**Comment by jaw187** [comment]
The data is accessible via `request.auth.credentials.someData` and it will be available on the subsequent requests that occur after your call to `request.auth.session.set`

**Comment by rainabba** [comment]
Ahh. Not being available until the next request is what got me. Doesn't feel like a session variable that way so much as a cookie value (which I realize it technically is).
