### ISSUE TITLE
How to setup session from inside another provider

### ISSUE THREAD

**Issue by rainabba** [hapijs/hapi-auth-cookie#87]
I'm using [hapi-auth-jwt2](https://github.com/dwyl/hapi-auth-jwt2) for an additional strategy and inside the validate function there, when the user is authenticated by a valid token, I'd like to setup a session so that future requests are valid per hapi-auth-cookie.

I expected this to be as simple as calling `request.auth.session.set( creds );` inside that validate function, but I don't see the hapi-auth-cookie being returned. Is this approach fundamentally broken? Do I need to hack around this functionality?

Thanks in advance for any help here.

**Comment by rainabba** [comment]
It appears that I am seeing the expected behavior on one route (swagger), but not another one where I'm calling `reply( JSON.stringify(res) ).type('application/json');`

Digging deeper, I see the cookie in the set-cookie header, but it's not being applied/saved. Stranger still is that I see the cookie from YAR also (after the hapi-auth-cookie one) and it IS being saved. The only difference I see is the YAR cookie is not set HttpOnly. That explain it and is that expected if so?

**Comment by jaw187** [comment]
Would you be able to post a gist or a repo with the simplest example of the problem?

**Comment by jaw187** [comment]
@rainabba ^^^
