### ISSUE TITLE
Example for invalidating another session

### ISSUE THREAD

**Issue by bf** [hapijs/hapi-auth-cookie#89]
First of all thanks for this very nice piece of software. I'm currently stuck trying to figure out how to best solve the following situation:

A user has multiple sessions, e.g. one in Chrome and one in Firefox. Now they use Chrome to change their password, and I want to invalidate not only the session in Chrome but also the session in Firefox. 

I observed `request.auth.session.clear()` to only remove the cookies for the Chrome browser which is pretty straightforward. If I want to invalidate the cookie of the Firefox browser, how does one proceed?

I can imagine:

1) Store a `token` in both the database and the session credentials, and use `validateFunc` to check if the token in credentials is still present in the database.
2) Store a `last_change_timestamp` together with the password in the database, and only accept auth cookies created after this point in time.

I am unsure whether 1) or 2) are optimal approaches in this situation, and although one could do some caching it seems like it might add some load.

Could you give me a pointer into the right direction please?

**Comment by jaw187** [comment]
There isn't anyway getting around utilizing some type of shared storage for two totally separate requests to be related.  I'd say go with what ever implementation you think your more comfortable with, they both seem quite similar to me.

**Comment by bf** [comment]
Thanks for clarifying, your framing of the issue helped me to understand it better. I've implemented it now using a centralized storage which links all sessions.
