### ISSUE TITLE
Example using catbox-redis for session storage

### ISSUE THREAD

**Issue by thebinarypenguin** [hapijs/hapi-auth-cookie#90]
I'm using hapi-auth-cookie for my session/state management however I would like to make my hapi server stateless (and scalable) by offloading session storage to a redis server using catbox-redis.

Do you have any examples of how to use hapi-auth-cookie and catbox-redis together?

**Comment by hueniverse** [comment]
https://github.com/npm/newww/blob/master/lib/startup.js#L62

**Comment by thebinarypenguin** [comment]
Oops, I didn't realize there was an example in the repo.

https://github.com/hapijs/hapi-auth-cookie/blob/master/example/index.js 

Between this example and the one from npm/newww that should do it thanks.
