### ISSUE TITLE
auth.session.set secure/best approach?

### ISSUE THREAD

**Issue by ravisuhag** [hapijs/hapi-auth-cookie#92]
My user object looks like this. 
```
var user = {
    id : "",
    name : '',
    username :'',
    gender : '',
    location :'',
    resetToken :'',
    pass : '',
    salt : ''
}
```
I am concerned, which one is best approach in terms of security, cookie size, performance etc. 
```
request.auth.session.set(user);
```
or 
```
request.auth.session.set(user.id);
```

**Comment by ravisuhag** [comment]
@jaw187 can you help me out?

**Comment by jaw187** [comment]
@ravisuhag I don't think you'll see a difference in the size of the cookie if you use `user` or `user.id`.  Cookies are going to be encrypted with Iron, so you should have some confidence that it's secure and performant.

**Comment by ravisuhag** [comment]
Great. This approach will save few DB queries for me.
