### ISSUE TITLE
Node >= 4 / es6 updates

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapi-auth-cookie#93]
Summary of changes required:

- use strict
- `const` and `let` where appropriate (linter will tell you where)
- arrow functions where appropriate (linter will tell you where)
- relevant updates to tests + docs
- updating deps and engine in package.json
- avoid `self` and `+=` / `-=` (not optimized yet for let const)

**Comment by jaw187** [comment]
@mtharrison Thanks Matt, I'll take it from here.

https://github.com/hapijs/contrib/issues/62

**Comment by jaw187** [comment]
Addressed by #102
