### ISSUE TITLE
logout issue

### ISSUE THREAD

**Issue by wh33lhouse** [hapijs/hapi-auth-cookie#95]
I have noticed a potential security issue, and would like some assistance/clarification.  DM me for more details.  Thanks.

**Comment by jaw187** [comment]
@wh33lhouse Not familiar with a way to DM via GitHub, but go ahead and email me directly.  jawone87 AT gmail DOT com

**Comment by jaw187** [comment]
@wh33lhouse Ok to close?

**Comment by wh33lhouse** [comment]
Oh yeah, sorry, I got swamped last week and forgot.  But yes.  Thanks!

~Dan
