### ISSUE TITLE
support these options: ignoreErrors, strictHeader, passThrough, autoValue

### ISSUE THREAD

**Issue by paulovieira** [hapijs/hapi-auth-cookie#96]
The `server.state` method accepts a bunch of options that control the processing of cookies. This plugin currently supports the following options:

  - password
  - ttl
  - domain
  - path
  - clearInvalid
  - isSecure
  - isHttpOnly
 
The following 2 options are also present in the plugin, but are hard-coded (so they're not really options):

  - ignoreErrors
  - encoding

So the following 7 options are missing and could be supported:

  - ignoreErrors
  - encoding
  - strictHeader
  - passThrough
  - autoValue
  - sign
  - iron

From these, the options relative to Iron (`encoding`, `sign`, `iron`) are maybe a bit too low-level, so they could be hidden from the user. But the remaining 4 could be easily added:

  - ignoreErrors
  - strictHeader
  - passThrough
  - autoValue

I can make a pr if there is green light to  merge.

**Comment by jaw187** [comment]
I don't see any problem adding to the options.  Go ahead and send in a PR.

**Comment by jaw187** [comment]
@paulovieira Are you still looking to make these changes?

**Comment by paulovieira** [comment]
Sorry for the delay. I wanted to send the pr, but I making the tests for these options was not trivial for me. I currently don't have time for that, sorry.

**Comment by jaw187** [comment]
Closing issue for now, feel free to reopen when you can
