### ISSUE TITLE
Having Trouble with implementing single session per user?

### ISSUE THREAD

**Issue by tezlopchan** [hapijs/hapi-auth-cookie#97]
I have flagged a user with isLogged in db when user is logged in, but having trouble to set is false when the session expires after certain time. How can we flag islogged false when session expires after some time

**Comment by jaw187** [comment]
Your approach may be wrong.  If you're expecting the cookie to expire, you'll have no way of notifying the database that the cookie expired.  You could add a column to track the expiration date and implement a routine to review sessions.  

But I think most people are using a similar flag to indicate when a user with a valid cookie should not be logged in.

**Comment by jaw187** [comment]
@tezlopchan Ok to close?

**Comment by tezlopchan** [comment]
Thanks for Info... I create a new collection in mongodb and set auto expire time for session id and did some checking.. its working for now..
