### ISSUE TITLE
Is there any way to access my client cookie? Or way to clear client cookie on Browser close?

### ISSUE THREAD

**Issue by tezlopchan** [hapijs/hapi-auth-cookie#98]
I was trying to get access to my client cookie but seems we cannot.. But we can manually clear the session from dev tools options.

**Comment by hueniverse** [comment]
Make sure `isHttpOnly` is set to `false`.

**Comment by tezlopchan** [comment]
:+1:

**Comment by tezlopchan** [comment]
:+1:
