### ISSUE TITLE
How does ttl work?

### ISSUE THREAD

**Issue by tezlopchan** [hapijs/hapi-auth-cookie#99]
i see in documentation, 
```
ttl - sets the cookie expires time in milliseconds. 
Defaults to single browser session (ends when browser closes).
```

Says defaults to single browser session and ends when browser closes but even if i close browser the session exist?

**Comment by mtharrison** [comment]
It's up to your browser when it delete a cookie with session expiry. Are you using Chrome? Perhaps this will help: http://stackoverflow.com/a/10772420/1402929
